server:
  port: 8100

spring:
  application:
    name: lab-rabbitmq
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 1

logging:
  level:
    com.codeself.lab.rabbitmq: debug

# Module: RabbitMQ
# Description: Simple Queue, Work Queue, Pub/Sub, Routing, Topic
